PACKAGE_NAME="nitro-sense"
PACKAGE_VERSION="0.1.0"
BUILT_MODULE_NAME[0]="nitro_sense"
DEST_MODULE_LOCATION[0]="/kernel/drivers/platform/x86"
MAKE[0]="make KVER=${kernelver}"
CLEAN="make clean"
AUTOINSTALL="yes"
